### ISSUE TITLE
gulp watch fail in liferay 7.1 due changes on gogo shell

### ISSUE THREAD

**Issue by backtime** [liferay/liferay-themes-sdk#113]
Connecting to gogo shell in 7.1 (7.1.1 CE GA2) show a welcome's message like the one below
**____________________________
Welcome to Apache Felix Gogo
g!**

This message seems to generate confusion on parsing command responses sent via GogoShell.sendCommand(), _getWebBundleData() is not able to retrive the bundle ID 
anymore and in general data returned from sendCommand() it's full of garbage.

**Comment by jbalsas** [comment]
Hey @backtime, thanks for reporting!

We're already tracking this in https://github.com/liferay/liferay-themes-sdk/issues/113. There's some additional information there that you can check.

We think we've identified the source of the problem and will attempt to fix this during the next days.

Please, watch https://github.com/liferay/liferay-themes-sdk/issues/113 for more details!

**Comment by backtime** [comment]
Hi @jbalsas , thanks for reply, may be I'm wrong but #113 is this issue, what is the issue number you talk about?

**Comment by jbalsas** [comment]
You're of course right, @backtime, my bad! I meant https://github.com/liferay/liferay-themes-sdk/issues/102 :)
