### ISSUE TITLE
7.1 Theme build fails due to missing import

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-themes-sdk#128]
After upgrading from 7.0 to 7.1, the theme fails building due to missing import.

Steps Customer Made:
1. Check current modules version
```
$> npm -g ls --depth=0
　/home/liferay/.npm-packages/lib
　├── generator-liferay-theme@7.2.0
　├── gulp@3.9.1
　└── yo@2.0.5
$> npm ls --depth=0
　sample-theme@1.0.0 /home/liferay/sample-theme
　├── gulp@3.9.1
　├── liferay-theme-deps-7.0@1.2.1
　└── liferay-theme-tasks@1.5.0
```

2. Upgrade node modules to 7.1 version
```
$> npm install --save-dev liferay-theme-deps-7.0@8.0.0-rc.1
$> npm install --save-dev liferay-theme-tasks@8.0.0-rc.1
$> npm ls --depth=0
sample-theme@1.0.0 /home/liferay/sample-theme
├── gulp@3.9.1
├── liferay-theme-deps-7.0@8.0.0-rc.1
└── liferay-theme-tasks@8.0.0-rc.1

```
3. Manually fix known issue
https://github.com/liferay/liferay-themes-sdk/issues/125
`$> sed -i 's/bgblack/bgBlack/g' ./node_modules/liferay-theme-tasks/lib/upgrade/7.0/upgrade.js`

4. Upgrade theme to 7.1
`$> gulp upgrade`

5. Follow the guide to upgrade the remaining parts "gulp upgrade" does not cover
https://help.liferay.com/hc/en-us/articles/360017887772-Upgrading-Your-Theme-from-Liferay-Portal-7-0-to-7-1-

6. Deploy upgraded theme
`$> gulp deloy`

7. Reported error is displayed
```
Exception in thread "main" com.liferay.sass.compiler.jni.internal.JniSassCompilerException: Error: no mixin named text-overflow

       Backtrace:
           build/buildTheme/css/portlet/_topper.scss:90
        on line 90 of build/buildTheme/css/portlet/_topper.scss
>>     @include text-overflow;
   ----------^

    at com.liferay.sass.compiler.jni.internal.JniSassCompiler.compileFile(JniSassCompiler.java:164)
    at com.liferay.css.builder.CSSBuilder._parseSass(CSSBuilder.java:380)
    at com.liferay.css.builder.CSSBuilder._parseSassFile(CSSBuilder.java:394)
    at com.liferay.css.builder.CSSBuilder.execute(CSSBuilder.java:160)
    at com.liferay.css.builder.CSSBuilder.main(CSSBuilder.java:79)
:wars:class-them:buildCSS FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wars:class-them:buildCSS'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.752 secs
```

Reported workaround to add this include in "_imports.scss"
`@import "compat/mixins";`

Shouldn't the "gulp upgrade" process add this missing import automatically?
Let me know if more information is needed.

Thank you.

**Comment by Ramalingaiah** [comment]
Working Directory: E:\workspace\projectWorkspaceNew\wars\Sample
Gradle user home: C:\Users\DudimetlaRamalingaia\.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 4.10.2
Java Home: C:\Program Files (x86)\Java\jdk1.8.0_201
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: buildCSS

> Task :wars:Sample:buildTheme

> Task :wars:Sample:buildCSS
Using native Sass compiler
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Parsed /css/clay/atlas-variables.scss in 778ms
Parsed /css/clay/atlas.scss in 3098ms
Parsed /css/clay/base-variables.scss in 217ms
Parsed /css/clay/base.scss in 2527ms
Parsed /css/clay/bootstrap/bootstrap-grid.scss in 143ms
Parsed /css/clay/bootstrap/bootstrap-reboot.scss in 51ms
Parsed /css/clay/bootstrap/bootstrap.scss in 462ms
Parsed /css/clay/bootstrap.scss in 593ms
Parsed /css/clay/site/site-atlas-font-awesome.scss in 2837ms
Parsed /css/clay/site/site-lexicon-font-awesome.scss in 2468ms

> Task :wars:Sample:buildCSS FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wars:Sample:buildCSS'.
> Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_201\bin\java.exe'' finished with non-zero exit value -1073741819

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 5s
2 actionable tasks: 2 executed
i am getting error
please help me 
thank you

**Comment by wincent** [comment]
Hi @Ramalingaiah. Would you be able to create a separate issue for this, along with a enough information to repro the issue? (For example, the command you ran to produce this output, and possibly the theme files themselves if you are able to provide them?)

**Comment by krishnaapatel** [comment]
This solution work for me from [link](https://chingovan.blogspot.com/2019/05/liferay-7-error-while-buildcss.html),

the easiest way to fix it is using the previous one.
To use a specify version of css builder we need to add line:

`cssBuilder group: "com.liferay", name: "com.liferay.css.builder", version: "2.1.3"`

into the dependences sector at file build.gradle and rebuild your project.
