### ISSUE TITLE
Deprecation support in the generator

### ISSUE THREAD

**Issue by natecavanaugh** [liferay/liferay-themes-sdk#15]
Heya @jbalsas @izaera 
As I've been looking through the SDK, I noticed in the generator-liferay-theme that you guys had done some refactoring to the deprecation support.

What I'm noticing is a bit different than what I was expecting, and wanted to clear it up with you guys on what the intent is before submitting a pull to "fix" it.

### What is currently happening
- Just running `yo liferay-theme`
    - After selecting 7.1 as my Liferay version, it prompts for me to choose a language, but only .FTL is supported
    - If I choose 7.0, it skips the question, and immediately goes to the `npm install` portion of the lifecycle.

- Running `yo liferay-theme --deprecated`
    - After selecting 7.1, it still prompts me to choose a language, but only Freemarker is listed
    - If I choose 7.0, it will prompt me to choose between Velocity and Freemarker

### What I expect to happen
- Just running `yo liferay-theme`
    - After selecting 7.1 as my Liferay version, it should immediately skip the question and go to `npm install`
    - If I choose 7.0, it should behave as 7.1 (no question prompted)

- Running `yo liferay-theme --deprecated`
    - This one is probably the most questionable, but I'm assuming we're officially dropping Velocity support as of 7.1, so I would imagine it would still skip the prompt
    - If I choose 7.0, it should prompt as it does now

I think my question is twofold: 1, do you guys agree that the way I typed above is correct, and 2, whether or not we want to keep Velocity as a deprecated option (I'm doubting it, but wanted to check first rather than assuming).

If you guys agree on my expectations, I can submit a pull to change that portion.

Thanks guys :)

**Comment by jbalsas** [comment]
Hey @natecavanaugh, thanks a lot for looking into this!

I agree with your expectations. We removed velocity support for theme templates in 7.1, so yeah, there's no sense in supporting it under deprecated for a `7.1.` theme.

Feel free to go ahead with the PR in that direction :)

**Comment by izaera** [comment]
@natecavanaugh : there’s a thing called [divert](https://github.com/liferay/liferay-themes-sdk/tree/master/packages/generator-liferay-theme/lib/divert) in the theme generator. It’s not as good as I would like it to be, but I introduced it as a first attempt to manage different target versions.

The rationale behind it is that modules loaded with “divert” use the code in [common](https://github.com/liferay/liferay-themes-sdk/tree/master/packages/generator-liferay-theme/lib/divert/common) except if there is an specific folder for the version being targeted ([7.0](https://github.com/liferay/liferay-themes-sdk/tree/master/packages/generator-liferay-theme/lib/divert/7.0) in this case). 

For example, in [this line](https://github.com/liferay/liferay-themes-sdk/blob/afa258e0f99be2a14d31e969ec812016531114aa/packages/generator-liferay-theme/generators/app/index.js#L176) the divert call loads [this](https://github.com/liferay/liferay-themes-sdk/blob/master/packages/generator-liferay-theme/lib/divert/7.0/app_helpers.js) when the target version is 7.0, and [this](https://github.com/liferay/liferay-themes-sdk/blob/master/packages/generator-liferay-theme/lib/divert/common/app_helpers.js) for any other target version (currently it could only be 7.1). Of course, as you may have guessed, both files export the same interface.

Take a little time to understand how it works and if you have any doubt, don't hesitate to ask.

Cheers :-)
