### ISSUE TITLE
Error when we search a themelet in NPM

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-themes-sdk#17]
1º Gulp extend in your theme
2º Select themelet
3º Select Search npm registry (published modules)

`(node:31516) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): HTTPError: Response code 404 (Not Found)
(node:31516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

![image](https://user-images.githubusercontent.com/7963804/42089977-cc5d01d4-7b9f-11e8-94df-756bbc29d130.png)

**Comment by jbalsas** [comment]
I'm looking into this... related dependencies need to be updated `package-json` and `npm-keywords` and APIs have changed that need udpating

**Comment by jbalsas** [comment]
Fixed in `v8.0.0-beta.1`
