### ISSUE TITLE
gulp watch crashes after restart on Windows 10

### ISSUE THREAD

**Issue by chrberndt** [liferay/liferay-themes-sdk#18]
The gulp watch crashes after restart on Windows 10. The issue seems  to be caused by a problem with uninstalling the theme's OSGI bundle. 

How to reproduce: 

1. Install liferay-7.1-b3 on Windows 10
1. Set include-and-override=portal-developer.properties in portal-ext.properties
1. Startup liferay with startup.bat
1. Install node, yeoman, gulp, and generator-liferay-theme as documented at https://dev.liferay.com/de/develop/tutorials/-/knowledge_base/7-1/creating-themes
1. Create a new theme with yo liferay-theme
1. Deploy the newly generated theme with gulp watch (will launch live preview with chrome on port 9089)
1. Login in to Liferay and select the generated theme as theme for the default site
1. Modify the theme (e.g. set background-color: red for body tag in my-liferay-theme/src/css/_custom.scss)
1. Reload the browser at localhost:8080 (if its not automatically reloaded at port 9080) - body background is red
1. Modify the theme (e.g. set background-color: cyan for body tag in my-liferay-theme/src/css/_custom.scss)
1. Reload the browser at localhost:8080 (if its not automatically reloaded at port 9080) - body background is cyan
1. Stop gulp watch task in cmd window with CTRL-C
1. Restart gulp watch in the same cmd window
1. [22:18:31] Starting 'watch:clean'...
1. gulp crashes with the message below: 
<pre>
[22:19:24] 'watch:clean' errored after 53 s
[22:19:24] Error: EBUSY: resource busy or locked, unlink 'C:\liferay\my-liferay-theme\.web_bundle_build\WEB-INF\lib\util-bridges.jar'
C:\liferay\my-liferay-theme\node_modules\liferay-theme-tasks\tasks\watch.js:50
                                        throw err;
                                        ^
Error: EBUSY: resource busy or locked, unlink 'C:\liferay\my-liferay-theme\.web_bundle_build\WEB-INF\lib\util-bridges.jar'
</pre>
1. Reload browser at localhost:8080 - screen remains blank
1. Connect to gogo shell with: telnet localhost 11311
1. Uninstall the broken theme-bundle with: uninstall bundle-id
1. Relaunch gulp watch in cmd window
1. Reload browser at localhost:8080 - theme is working again
1. Modify _custom.scss
1. Reload browser at localhost:8080 - modification is visible in browser 

Expected behaviour: 

A frontend developer using Windows 10 should be able to stop and restart the gulp watch task without having to uninstall the theme manually via the gogo shell.

Additional note: 

If you use both, gulp deploy and gulp watch, you end up with two themes deployed with the same name, since one is installed via fileinstall and the other via the deploy process. 

Since this is a common mistake which must be expected to be made from users (the current training material for 7.1 Frontend Development suggests this usage pattern, too), the gulp watch task should take care of uninstalling themes of the same name and version installed via the deploy process before installing them via fileinstall / gogo shell.

**Comment by natecavanaugh** [comment]
Thanks @chrberndt just for anyone who is watching the original filing on https://github.com/liferay/liferay-theme-tasks/issues/85 We are looking at this.
Since many of us don't use Window's, it's been a little tough to track down, but my thinking is that it could possibly be an issue with a mix of Window's file locking behavior in general, and perhaps an issue in the [gogo-shell-helper](https://www.npmjs.com/package/gogo-shell-helper) package that's not properly releasing the lock on the util-bridges.jar file.
It could also just be a weird quirk of the Windows file system (but my gut tells me that even if so, there should be a workaround), but as soon as we know, we'll push in a fix (or update this comment to reflect if we're not able to fix it from our end).

@jbalsas have you guys experienced this issue at all?

**Comment by jbalsas** [comment]
Hey @natecavanaugh, we haven't had the chance to do extensive testing on Windows and were hoping  to put in some time soon.

I'll reach out to some people to see if they've run into this.

**Comment by chrberndt** [comment]
Hi @natecavanaugh , Hi @jbalsas , thank you very much for looking into this! I understand that Windows compatibility might not be your first priority in testing but for us in Training it's in fact the most relevant platform. The majority of my trainees attends our trainings with Windows laptops and for a lot of them it's their first contact with Liferay Tooling.

**Comment by jbalsas** [comment]
Hey @chrberndt, windows compatibility is indeed one of our priorities. We'll get to it as soon as we can, but provisioning and setting up windows machines takes some time.

As I said, we'll look into it and we're aware of the importance of this for training. Of course, we'd also appreciate any additional help we could get :)

**Comment by izaera** [comment]
The PR doesn't fix the `Additional note` problem stated in [this comment](https://github.com/liferay/liferay-themes-sdk/issues/18#issue-337150087). It will be addressed in the future.
