### ISSUE TITLE
Using gulp extend searching for themelet results in error

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-themes-sdk#33]
package: liferay-theme-tasks
version: 8.0.0-beta.1

I am running into 404 errors while using `gulp extend` trying to find themelets. I have tried various themelets with no luck. Currently using Node v6.12.3 npm 6.2.0 on windows. If any more information is needed please let me know.

![gulpextend](https://user-images.githubusercontent.com/31672551/43223575-63fc16d4-9008-11e8-9241-56bfe2109550.PNG)

**Comment by jbalsas** [comment]
Hey @fortunatomaldonado, was this still an issue in Windows?

We might move to https://github.com/npm/libnpmsearch for a more consistent search... 🤔

**Comment by jbalsas** [comment]
Hey @fortunatomaldonado, I've just confirmed this is still an issue in `8.0.0-beta.1`, but is already fixed for the upcoming `8.0.0-beta.2` which should be out before the end of the week.
