### ISSUE TITLE
Upgrade task should warn about expected portlet_header dynamic-include extension point

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-themes-sdk#35]
In updated themes, we are adding a dynamic include extension point so applications can contribute content to a portlet header:

```ftl
<@liferay_util["buffer"] var="portlet_header">
	<@liferay_util["dynamic-include"] key="portlet_header_${portlet_display_root_portlet_id}" />
</@>

...

<#if portlet_header?has_content>
	<div class="autofit-col autofit-col-end">
		<div class="autofit-section">
			${portlet_header}
		</div>
	</div>
</#if>
```

We should include this in the upgrade tool for a better upgrade process

**Comment by yuchi** [comment]
Tangential question: why are you not using the extended Freemarker assign directive (`<#assign> … </#assign>`) instead of `<@liferay_util.buffer />`?

**Comment by jbalsas** [comment]
That's a good point, @yuchi! I'll look into that... not sure if we have a specific reason, so probably we might be able to defer to Freemarker syntax as you suggest!
