### ISSUE TITLE
Remove alloy-font-awesome import during upgrade task from a 6.2 theme

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-themes-sdk#36]
I think we should remove this imports from _custom.scss during upgrade 6.2 theme process:

```
@import "aui/alloy-font-awesome/scss/mixins-alloy";
@import "aui/alloy-font-awesome/scss/variables";
```

**Comment by marcoscv-work** [comment]
Some themes like manzanita use those imports to use mixins and variables, if you have some of them your 7.0 or 7.2 theme will not compile so it has to be removed from your CSS, automatically or manually:

https://github.com/marcoscv-work/manzanita-theme/blob/adb5d0cd19bc44d3b7f1f0700bb79b9ef1103365/docroot/_diffs/css/custom.css#L1-L2

Those imports are common to use because are present in very used 'plugins' for dockbar like:

https://github.com/marcoscv-work/experimental-liferay-themes/blob/master/dockbar-classic-theme/docroot/_diffs/css/dockbar_classic.css#L1-L2
or 
https://github.com/marcoscv-work/experimental-liferay-themes/blob/master/dockbar-vertical-theme/docroot/_diffs/css/dockbar_vertical.css#L1-L2

**Comment by jbalsas** [comment]
So... when did we remove those files? Was it in `7.0` or was it in `7.1.`?
