### ISSUE TITLE
Upgrade task overwrites properties in package.json with incorrect values

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-themes-sdk#37]
After running `gulp upgrade` for my 6.2 theme, the task changed my `package.json` `ruby-sass` value from `true` to `false`. After running the task a second time to upgrade the 7.0 theme to 7.1, it changes the `liferay-theme-tasks` and `liferay-theme-deps-7.0` dependency values from the latest `8.0.0-beta.1` to `8.0.0-alpha.6`, a previous version.

**Comment by izaera** [comment]
The above commit fixes the bug when upgrading from 7.0 to 7.1, but not from 6.2 to 7.0. That will be sent in another PR to a different branch.
