### ISSUE TITLE
Allow different base font sizes

### ISSUE THREAD

**Issue by sbaechler** [liferay/liferay-themes-sdk#44]
The admin UI should not depend on a certain base font size. Since it changed From 10px in Liferay 7 to 16px in 7.1 I guess most people that just upgraded have changed it back.

This caused issues in a few places in the admin interface (see screenshots).

![lr-font-size1](https://user-images.githubusercontent.com/288516/44576588-35d34400-a78f-11e8-8011-e019b76bb1c3.png)
![lr-font-size2](https://user-images.githubusercontent.com/288516/44576599-3966cb00-a78f-11e8-989a-fb80d84c843f.png)

If you used Bootstrap `$font-size-base` variable instead of rem values, it would be fine.

This code patched the issues that I have found so far:

```
$custom-control-indicator-size: 1em;

.admin {
  .control-menu-level-1-heading {
    font-size: $font-size-base;
  }

  .product-menu .list-group-heading.goto-link {
    font-size: $font-size-base * 0.8;
  }

  .custom-control label {
    font-size: $font-size-base;
  }
}
```
This issue was also mentioned in https://github.com/liferay/clay/issues/1104 (among others).

**Comment by jbalsas** [comment]
Hey @sbaechler, this is not something related to the tool itself, but to the underlying themes we're using.

Following on https://github.com/liferay/clay/issues/1104, @pat270 opened https://github.com/liferay/clay/issues/1318 for discussion.

Would you mind weighing in there?

I'm closing here for now, but please, reopen if you think there's something we could/should do on the tool level.

Thanks!
