### ISSUE TITLE
Theme dependent on another OSGi bundle: how?

### ISSUE THREAD

**Issue by caneta** [liferay/liferay-themes-sdk#49]
As mentioned [here](https://github.com/liferay/liferay-theme-tasks/issues/34#issuecomment-416271434), I would like to know how to make a gulp created theme dependent to another OSGi bundle.
It's not clear to me why Liferay 7 have 2 different approaches to create themes: [forum thread here](https://community.liferay.com/it/forums/-/message_boards/view_message/99776351).
Any hints?

**Comment by jbalsas** [comment]
Hey @caneta, **Node.js is not an approved technology for many companies**. As such, we need to provide a valid approach for such cases. Being that the only option many companies have, he could decide to just develop the Java-way. 

However, we're convinced the frontend world is full of opportunities and innovation and we want to provide a friendly platform for frontend developers as well. We want to see all those new ideas pour into the product and the community.

Is for this reason that we think it's worth invest in both lines of development. One out of necessity, the other out of our desire to expand our developer-base.

Regarding what you mention about OSGi... what would you want to do with that dependency? I assume you want to include some files in your theme? I'd say you could either:
- Create a theme hook to download and expand your released artifact, maybe with https://www.npmjs.com/package/mvn-artifact-download so that becomes available
- Publish your artifact to npm and consume it as a dependency from `package.json`

Does this address your questions?

**Comment by caneta** [comment]
Thank you for your answer about the node development of Liferay 7 theme, now the topic is clearer to me.

About dependency of OSGi I did not intend files inside my theme, but bundles like portlets.

Let's say I have to make **my-bundle-big.jar** dependent by **my-bundle-small.jar**. With Gradle I can put inside _build.gradle_ file of **my-bundle-big.jar** `dependencies {compile project(":modules:my-bundle-small")}` and I will get in the builded jar, inside _MANIFEST.MF_ file, something like `Import-Package: my-package-small`: in this way when I deploy **my-bundle-big.jar** the Liferay OSGi system knows at runtime that I need **my-bundle-small.jar** as a dependency to use **my-bundle-big.jar**.

How to do the same thing with a theme developed with Gulp where I do not a have a _build.gradle_ file? How to tell to **my-theme.war** to be dependent at runtime to, let's say, **my-bundle-small.jar**?

**Comment by jbalsas** [comment]
Hey @caneta, glad to help out clarify this.

So, continuing with your OSGi question. As far as I can tell, our [`WabProcessor`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/static/portal-osgi-web/portal-osgi-web-wab-generator-impl/src/main/java/com/liferay/portal/osgi/web/wab/generator/internal/processor/WabProcessor.java#L1073) reads from the `liferay-plugin-package.properties` to [generate the proper headers](https://github.com/liferay/liferay-portal/blob/master/modules/apps/static/portal-osgi-web/portal-osgi-web-wab-generator-impl/src/main/java/com/liferay/portal/osgi/web/wab/generator/internal/processor/WabProcessor.java#L1106), and will transfer those to your `MANIFEST`.

I think an example is how [we're providing a `Provide Capability` header in the Marketplace themes](https://github.com/liferay/liferay-portal-ee/blob/7.0.x/modules/apps/frontend-theme-porygon/frontend-theme-porygon/src/WEB-INF/liferay-plugin-package.properties#L11)

I'm not an expert here, so let me know if this is not what you're looking for so I can do some additional digging ;)

**Comment by jbalsas** [comment]
Ooopsies... wrong repo! Fixed now :)

https://github.com/liferay/liferay-portal/blob/7.0.x/modules/apps/frontend-theme-porygon/frontend-theme-porygon/src/WEB-INF/liferay-plugin-package.properties#L11

**Comment by caneta** [comment]
At the moment I can't try this out, sorry. Close it if you feel to, don't worry.

**Comment by jbalsas** [comment]
Thanks @caneta!

I can confirm that adding the following headers to a `liferay-plugin-package.properties`

```
Import-Package=com.my.own.import.package
Other-Header=otherHeaderValue
```

results in the folllowing headers in the registered service

<img width="389" alt="screen shot 2018-09-11 at 12 05 07" src="https://user-images.githubusercontent.com/905006/45353397-fd1ed180-b5ba-11e8-8ddd-fe411e48d777.png">

@mwilliams2014, is this documented? Can you please add it if it isn't?

Thanks!

**Comment by caneta** [comment]
Thank you @jbalsas, it works!
The only thing we had to add was `Other-Header=otherHeaderValue`, otherwise our theme would not be registered inside the OSGi context.

**Comment by jbalsas** [comment]
Hey @caneta, you mean you actually had to add that specific garbage header? 🤔 

If so, I think I'll probably need to take a closer look to see what might be wrong there 😂

**Comment by caneta** [comment]
Sorry about that, the `Other-Header=otherHeaderValue` was just a placeholder that we **removed** (not added as I stated before) from the _liferay-plugin-package.properties_ file inside our theme.

What we actually do was modify 2 files: _bnd.bnd_ of the OSGi module we want as a dependency of our theme:
```
Export-Package: our.dependency.package
```
and _liferay-plugin-package.properties_ inside our theme adding the actual import (which does not work without the export above):
```
Import-Package=our.dependency.package
```

**Comment by jbalsas** [comment]
That makes total sense, thanks! 👍
