### ISSUE TITLE
Fix Sourcemap support for libsass

### ISSUE THREAD

**Issue by sbaechler** [liferay/liferay-themes-sdk#81]
Currently SourceMap support is disabled in the`build_compile-lib-sass` build task.

Why is this? Sourcemaps are very helpful.

**Comment by jbalsas** [comment]
Hey @sbaechler, do you mean you expect the sourcemaps to be enabled by default? 

Currently, you should be able to set `sassOptions.sourceMap` to `true` to generate sourcemaps.

**Comment by sbaechler** [comment]
I apologize. I missread the getSassOptions functions. The second arguments are the defaults, not the overrides. This is a bit confusing since in Javascript it is usually the other way round. E.g. Object.assign() or with Object destructing.
