### ISSUE TITLE
Erroneous update message: Update available 8.0.0-beta.1 → 8.0.0-beta.5

### ISSUE THREAD

**Issue by chrberndt** [liferay/liferay-themes-sdk#92]
Though I have successfully updated the generator-liferay-theme, I get the following message, after I've created my theme: 
```
   ╭────────────────────────────────────────────────────╮
   │                                                    │
   │   Update available 8.0.0-beta.1 → 8.0.0-beta.5     │
   │   Run npm i -g generator-liferay-theme to update   │
   │                                                    │
   ╰────────────────────────────────────────────────────╯
```
Environment Linux Debian 9

berndt@x270:~$ date; node -v; npm -v
Mon Sep 24 14:37:27 CEST 2018
v8.12.0
6.4.1

**Comment by wincent** [comment]
Discussing this earlier we decided to remove the update notifier functionality.
