### ISSUE TITLE
When using gulp:watch, activate theme by default

### ISSUE THREAD

**Issue by chrberndt** [liferay/liferay-themes-sdk#93]
For frontend-developers it would be great, to have a theme deployed with gulp:watch activated by default. Currently (8.0.0-beta.5), after a new theme has been deployed, it's in the Installed state and has to be activated manually (either at the gogo-shell or through the GUI).

**Comment by jbalsas** [comment]
Hey @chrberndt, thanks for reporting! That certainly shouldn't be the case... we'll investigate this!

**Comment by chrberndt** [comment]
@jbalsas it seems to be an issue on Linux - on 
Windows 10
C:\Users\Christian Berndt>javac -version
javac 1.8.0_181

my-liferay-theme is activated by default after gulp watch

**Comment by jbalsas** [comment]
I can confirm that it also starts properly on `OSX`... I'm not sure what can happen... maybe something with the watcher for the deployer in linux? 🤔

**Comment by jbalsas** [comment]
Just to be clear, the sequence you're following is:
- yo liferay-theme
- gulp watch

**Comment by chrberndt** [comment]
create a new theme with yo liferay-theme, 
cd into my-liferay-theme 
launch with gulp watch

I'm on Debian 9, but I will check tomorrow on Ubuntu, so that we have common playground -
if you were fine with installing an Ubuntu VM

**Comment by chrberndt** [comment]
no longer reproducible

**Comment by deadcyclo** [comment]
I'm experiencing the exact same issue, combined with #102 on ubuntu. What was done to fix this?
