### ISSUE TITLE
Product menu secondary panels (categories) white with an applied theme generated from yo liferay-theme

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-themes-sdk#98]
After applying the generated theme with default settings, the background color of the main product menu categories that are not expanded is white. When user clicks to expand a different panel-secondary category, the clicked panel-secondary no longer has a white background but the other two become or are still white.

**Comment by jbalsas** [comment]
Hey @john-co, this is an issue in Liferay Portal. I've filed https://issues.liferay.com/browse/LPS-86031 for this.
